//AUTH
export const LOADER = "LOADER"
//PRODUCTS
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_REVIEW = "ADD_REVIEW";
export const PRODUCT_CONFIRMATION = "PRODUCT_CONFIRMATION";

//CART
export const MODIFY_CART = "MODIFY_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TO_CHECK_CART_ITEM = "TO_CHECK_CART_ITEM";

//PAGINATION
export const PAGINATE_PRODUCTS = 'PAGINATE_PRODUCTS'
export const PAGINATE_CART = 'PAGINATE_CART';
