//PRODUCTS
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

//CART
export const MODIFY_CART = "MODIFY_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
